apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: elasticsearch
  name: elasticsearch
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: elasticsearch
    spec:
      containers:
      - env:
        - name: ES_JAVA_OPTS
          value: -Xms512m -Xmx512m
        - name: bootstrap.memory_lock
          value: "true"
        - name: cluster.name
          value: docker-cluster
        image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
        name: elasticsearch
        ports:
        - containerPort: 9200
        resources: {}
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: kuberneteselasticsearchclustermod-esdata1
      restartPolicy: Always
      volumes:
      - name: kuberneteselasticsearchclustermod-esdata1
        persistentVolumeClaim:
          claimName: kuberneteselasticsearchclustermod-esdata1
status: {}
