apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: es-data
  labels:
    component: elasticsearch
    role: data
spec:
  replicas: 2
  template:
    metadata:
      labels:
        component: elasticsearch
        role: data
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox:1.27.2
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
          # runAsNonRoot: true
          # runAsUser: 1000
          # capabilities:
          #   add: ["IPC_LOCK", "SYS_RESOURCE"]
      containers:
      - name: es-data
        image: servianclarke/elasticsearch:6.6.0-mod7
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: "SERVICE"
          value: "elasticsearch-cluster"
        - name: "DISCOVERY_SERVICE"
          value: "elasticsearch-discovery"
        - name: CLUSTER_NAME
          value: myesdb
        - name: NODE_MASTER
          value: "false"
        - name: NODE_INGEST
          value: "false"
        - name: NODE_DATA
          value: "true"
        - name: HTTP_ENABLE
          value: "true"
        - name: PATH_DATA
          value: "/data"
        - name: NETWORK_HOST
          value: _site_,_lo_
        - name: XPACK_SECURITY_ENABLE
          value: "false"
        - name: XPACK_SECURITY_AUDIT_ENABLE
          value: "false"
        - name: XPACK_MONITORING_ENABLE
          value: "true"
        - name: XPACK_ML_ENABLE
          value: "true"
        - name: XPACK_WATCHER_ENABLE
          value: "true"
        - name: URL_SLACK_MONITOR_HOOK
          value: "https://hooks.slack.com/services/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"
        - name: ES_JAVA_OPTS
          value: -Xms1g -Xmx1g
        - name: MEMORY_LOCK
          value: "false"
        - name: PROCESSORS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu
        resources:
          requests:
            cpu: 0.25
          limits:
            cpu: 1
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport
        livenessProbe:
          tcpSocket:
            port: transport
          initialDelaySeconds: 20
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /_cluster/health
            port: http
          initialDelaySeconds: 20
          timeoutSeconds: 5
        volumeMounts:
        - name: storage
          mountPath: /data
        - name: tmpstorage
          mountPath: /tmp
      volumes:
          - emptyDir:
              medium: ""
            name: storage
          - emptyDir:
              medium: ""
            name: tmpstorage
