apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: es-master
  labels:
    component: elasticsearch
    role: master
spec:
  replicas: 1
  selector:
    matchLabels:
      role: master
  template:
    metadata:
      labels:
        component: elasticsearch
        role: master
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox:1.27.2
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          # privileged: true
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            add: ["IPC_LOCK", "SYS_RESOURCE"]
      containers:
      - name: es-master
        image: herbertyeungservian/elasticsearch:6.6.0
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: "SERVICE"
          value: "elasticsearch-cluster"
        - name: "DISCOVERY_SERVICE"
          value: "elasticsearch-master-service"
        - name: CLUSTER_NAME
          value: esdb
        - name: NUMBER_OF_MASTERS
          value: "2"
        - name: NODE_MASTER
          value: "true"
        - name: NODE_INGEST
          value: "false"
        - name: NODE_DATA
          value: "false"
        - name: HTTP_ENABLE
          value: "false"
        - name: PATH_DATA
          value: "/data"
        - name: NETWORK_HOST
          value: _site_,_lo_
        - name: XPACK_SECURITY_ENABLE
          value: "false"
        - name: XPACK_SECURITY_AUDIT_ENABLE
          value: "false"
        - name: XPACK_MONITORING_ENABLE
          value: "true"
        - name: XPACK_ML_ENABLE
          value: "true"
        - name: XPACK_WATCHER_ENABLE
          value: "true"
        - name: URL_SLACK_MONITOR_HOOK
          value: "https://hooks.slack.com/services/..."
        - name: ES_JAVA_OPTS
          value: -Xms512m -Xmx512m
        - name: MEMORY_LOCK
          value: "false"
        - name: PROCESSORS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu
        resources:
          requests:
            cpu: 0.25
          limits:
            cpu: 1
        ports:
        - containerPort: 9300
          name: transport
        livenessProbe:
          tcpSocket:
            port: transport
          initialDelaySeconds: 20
          periodSeconds: 10
        volumeMounts:
        - name: storage
          mountPath: /data
      volumes:
          - emptyDir:
              medium: ""
            name: "storage"
